#!/usr/bin/env bash
# Install EVERY theme's SDDM greeter system-wide, then point SDDM at the active
# one.
#
# Separate from theme-apply.sh on purpose: SDDM runs as its own user and reads
# /usr/share/sddm/themes, not ~/.config — so this needs root, and the rest of
# theme switching shouldn't.
#
#   sudo ~/.config/hypr/scripts/sddm-apply.sh
#
# Installing ALL themes rather than only themes/current is what makes a later
# SUPER+T survivable: every greeter is already on disk, so re-running this
# after a switch only rewrites one line in the drop-in. A theme without an
# sddm/ dir is skipped, per the repo's rule that everything but theme.lua
# degrades gracefully.
set -euo pipefail

# Repo root from the script's own location — NOT $HOME, which is /root under
# sudo and would resolve to the wrong (nonexistent) clone.
REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
CUR="$REPO/themes/current"

[ "$(id -u)" -eq 0 ] || { echo "needs root: sudo $0" >&2; exit 1; }
[ -d "$CUR" ] || { echo "no active theme (themes/current missing)" >&2; exit 1; }

# install_greeter <theme-dir> — copy one theme's sddm/ into /usr/share.
install_greeter() {
    local src="$1" name dest wall
    name="hypr-$(basename "$src")"

    if [ ! -d "$src/sddm" ]; then
        echo "$name: no sddm/ dir — skipped"
        return 0
    fi

    dest="/usr/share/sddm/themes/$name"
    mkdir -p "$dest"
    cp -f "$src/sddm/"* "$dest/"

    # Ship the theme's wallpaper next to Main.qml and point theme.conf at it.
    #
    # Same glob-not-`ls` reasoning as theme_wallpaper() in scripts/theme-lib.sh
    # (ls output is not safely parseable — SC2012). Deliberately inlined rather
    # than sourced: this script runs as root under sudo and stays standalone, so
    # it gains neither a hard dependency under `set -e` nor a root-reads-a-
    # user-writable-sibling shape, for the sake of three lines.
    wall=""
    for w in "$src"/wallpaper.*; do [ -e "$w" ] && { wall="$w"; break; }; done

    # theme.conf is GENERATED, not shipped. It was byte-identical in every theme
    # and its only line was rewritten here anyway, so both tracked copies went
    # away. Writing it also means the greeter still installs when a theme ships
    # no wallpaper at all.
    printf '# Generated by scripts/sddm-apply.sh — edits here are overwritten.\n[General]\nbackground=%s\n' \
        "$([ -n "$wall" ] && basename "$wall")" > "$dest/theme.conf"

    if [ -n "$wall" ]; then
        cp -f "$wall" "$dest/"
        # Qt only decodes webp with the imageformats plugin installed.
        case "$wall" in *.webp)
            pacman -Q qt6-imageformats >/dev/null 2>&1 \
                || echo "warn: $name's wallpaper is webp but qt6-imageformats is not" \
                        "installed — that greeter's background will be black." \
                        "Fix: sudo pacman -S qt6-imageformats" >&2
        ;; esac
    fi

    # Normalize permissions: cp preserves the source's mode, and files that
    # arrive owner-only (600) would be unreadable to the sddm user — the greeter
    # then silently falls back to its embedded theme with "Permission denied".
    chmod 755 "$dest"
    chmod 644 "$dest"/*

    echo "installed $dest"
}

for theme in "$REPO"/themes/*/; do
    theme="${theme%/}"
    # themes/current is a symlink to one of its own siblings — following it
    # would install the active theme twice, under the name "hypr-current".
    if [ -L "$theme" ]; then continue; fi
    install_greeter "$theme"
done

active="hypr-$(basename "$(readlink -f "$CUR")")"

if [ ! -d "/usr/share/sddm/themes/$active" ]; then
    echo "active theme ships no sddm/ dir — login screen left unchanged"
    exit 0
fi

# Point SDDM at the theme via a drop-in (never edits /etc/sddm.conf itself).
mkdir -p /etc/sddm.conf.d
printf '[Theme]\nCurrent=%s\n' "$active" > /etc/sddm.conf.d/10-hypr-theme.conf

# ...but /etc/sddm.conf OUTRANKS /etc/sddm.conf.d/*.conf (sddm.conf(5): files
# load conf.d first, the compat file last, latter wins). A stray Current= there
# beats this drop-in with no error anywhere, which looks exactly like "the
# theme never installed". Cheap to detect, impossible to debug blind.
if [ -f /etc/sddm.conf ] && grep -Eq '^[[:space:]]*Current[[:space:]]*=' /etc/sddm.conf; then
    echo "warn: /etc/sddm.conf sets Current= and OUTRANKS this drop-in —" \
         "remove that line or the greeter will not change" >&2
fi

echo "set $active in /etc/sddm.conf.d/10-hypr-theme.conf"
echo "preview without logging out:  sddm-greeter-qt6 --test-mode --theme /usr/share/sddm/themes/$active"
